### ISSUE TITLE
Research: Advanced Search failing to generate expected search results

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#131]
**Problem Description:**
In advanced search, a search query was done where one of the expected results should be "Trumbull & Wiley". Instead of the expected results the query generated the "Your search yielded no results. Please try another search." message. If we change the query to go down to the [departmental level](https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F703438a0-4a84-4bc8-8c9c-28e8d3e944f8%22%7D%7D%7D%2C%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F1f8f20d5-a5e1-4422-8624-42debfe14eba%22%7D%7D%7D%5D%7D) the search results work. However, the results should also work at the non-departmental level. 

This ticket serves as a research ticket to understand why this is happening and how we can fix it. 

**Expected Behavior/Solution:**
TBD - research

**Requirements:**
TBD - research

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22group%2F0e8bc04a-6538-4792-b82a-9e0751857e7d%22%7D%7D%7D%7D%7D%2C%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22group%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%7D%7D%5D%7D (original search query - non departmental level) 

**Dependencies/Blocks:**
- Blocked By: Research

**Related Github Issues:**
- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2157

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment]
@roamye and @clarkepeterf,

Two responses:

1. Was this criteria created using the advanced search form?  As shown below, the IDs are missing the leading portion: `https://lux.collections.yale.edu/data/`.

```
{
  "AND":[
    {
      "produced":{
        "memberOf":{
          "curatedBy":{
            "memberOf":{
              "id":"group/0e8bc04a-6538-4792-b82a-9e0751857e7d"
            }
          }
        }
      }
    },
    {
      "produced":{
        "memberOf":{
          "curatedBy":{
            "memberOf":{
              "id":"group/6086b58d-941d-41e3-87c1-e00e96952ffb"
            }
          }
        }
      }
    }
  ]
}
```

2. Once corrected, the search and facet requests timeout after 20 seconds.  Looks like a pretty broad (and odd?) search: agents that produced objects that are part of a set whereby the set is curated by a group that is a member of YCBA _and_ YUAG.  Are any sets co-curated?  Or perhaps I'm misinterpreting the query.

**Comment by roamye** [comment]
@brent-hartwig 
1. Was this criteria created using the advanced search form? 
   A: I believe so. Sarah was this created in the AS form or was this from a link in LUX? 

cc: @prowns

**Comment by brent-hartwig** [comment]
It probably was and the user just didn't include the full URI/IRI.  It was probably one of us!  _If_ this was commonplace, the UI could provide a visual cue when the provided ID doesn't resolve and/or the backend could replace the associated CTS query containing an invalid ID with `cts.falseQuery`, thereby avoiding searching the triples store for something that will never exist.

**Comment by brent-hartwig** [comment]
@roamye, do we want to close this under the suspicion it was user error?

**Comment by prowns** [comment]
Likely, but first I am validating my search result: https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F0e8bc04a-6538-4792-b82a-9e0751857e7d%22%7D%7D%7D%7D%7D%5D%7D

**Comment by prowns** [comment]
Closing - works like a charm now.   Here it is with bibliographic and rare book materials as well.

https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22OR%22%3A%5B%7B%22created%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F0e8bc04a-6538-4792-b82a-9e0751857e7d%22%7D%7D%7D%7D%7D%7D%2C%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F0e8bc04a-6538-4792-b82a-9e0751857e7d%22%7D%7D%7D%7D%7D%5D%7D

**Comment by brent-hartwig** [comment]
Optimization debunked, at least for UAT example found in the description.  The query is for agents that have at least one object curated by YCBA and another by YUAG --not for agents that have objects co-curated by YCBA and YUAG.  As such, this is still a query that can time out and is being included as query 14 in the Optic/CTS comparison.

We also get to decide what to do about the v8 crash that followed the 8 Aug example (above).

**Comment by roamye** [comment]
@prowns @jffcamp - was a discussion had on the follow up procedure for this v8 engine crash scenario? 

should it be brought to the it team meeting?

**Comment by clarkepeterf** [comment]
Propose close:

-  Original description is a non-issue.
- Related performance improvements were made in https://github.com/project-lux/lux-marklogic/issues/304
- Further optimization can come from Optic switch

**Comment by brent-hartwig** [comment]
@clarkepeterf, let's see if I can pick this apart...

1. The original query did not use complete IRIs, leading to zero results.  We acknowledged we could help users should it happen frequent enough.
2. There may (or may not) be potential to consolidate queries that start and travel a portion of the same triples path at least twice.  Looking back at the attempts, it's simply not clear.  I see I corrected one of my mistakes but may have made another: [this YCBA or YUAG query](https://github.com/project-lux/lux-marklogic/issues/131#issuecomment-2358301362) uses AND.
3. The original query became query no. 14 of the Optic/CTS comparison.  That effort created a functionally and performant Optic equivalent of the CTS query.  While we have not started to create tickets for the switch to Optic, this will not be lost.
4. I'm not concerned about the v8 engine crash associated with the YCBA-only query.  We are imposing a 20 second timeout and should that elapse while the thread is in the v8 instance, that instance kabooms.  That should not lead to the ML process restarting, Engineering agrees, and we're tracking that separately.

Given the above, I propose we close this ticket. _:mic drop:_

**Comment by azaroth42** [comment]
It still doesn't work though?

https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22group%2F0e8bc04a-6538-4792-b82a-9e0751857e7d%22%7D%7D%7D%7D%7D%2C%7B%22produced%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F41310ca5-8137-45fe-ac2c-a6a04e2235f1%22%7D%7D%7D%7D%7D%5D%7D

**Comment by azaroth42** [comment]
Propose migrate the issue to front-end repo to fix how the URIs are sent.

**Comment by brent-hartwig** [comment]
> [with complete URIS] works as expected... a timeout lol ;)

This takes us back to:

3. The original query became query no. 14 of the Optic/CTS comparison. That effort created a functionally and performant Optic equivalent of the CTS query. While we have not started to create tickets for the switch to Optic, this will not be lost.

**Comment by jffcamp** [comment]
Should be less than a 1/2 day
